import pg from 'pg';
import { env } from './env.js'; // Importamos nuestro "traductor" de variables

const { Pool } = pg;

/**
 * 1. CONFIGURACIÓN DEL POOL
 * Usamos la URI que viene del .env a través de env.js
 */
export const pool = new Pool({
    connectionString: env.postgresUri,
    // Máximo de conexiones simultáneas (el equipo de trabajadores)
    max: 10, 
    // Tiempo máximo de espera para conectar (30 segundos)
    connectionTimeoutMillis: 30000, 
    // Tiempo de vida de una conexión inactiva antes de cerrarse
    idleTimeoutMillis: 10000 
});

/**
 * 2. VERIFICACIÓN DE CONEXIÓN
 * Este bloque es opcional pero MUY RECOMENDADO.
 * Al arrancar la app, intentamos una consulta simple para ver si 
 * el puerto 5433 de Docker realmente nos deja entrar.
 */
const testConnection = async () => {
    try {
        const client = await pool.connect(); // Pedimos una conexión al pool
        console.log(`\x1b[32m%s\x1b[0m`, `✅ PostgreSQL: Conexión establecida en el puerto 5433`);
        
        // Hacemos una consulta rápida para verificar que la DB responde
        const res = await client.query('SELECT NOW()');
        console.log(`\x1b[34m%s\x1b[0m`, `🕒 Hora del servidor DB: ${res.rows[0].now}`);
        
        client.release(); // Importante: devolvemos la conexión al pool
    } catch (err) {
        console.error(`\x1b[31m%s\x1b[0m`, `❌ PostgreSQL: Error de conexión`);
        console.error(`Detalle: ${err.message}`);
        console.error(`Revisa que tu contenedor de Docker esté corriendo y el puerto 5433 esté mapeado.`);
    }
};

// Ejecutamos la prueba de conexión
testConnection();



// import pg from 'pg';
// import { env } from "./env.js";

// const { Pool } = pg;

// export const pool = new Pool({
//     connectionString: env.postgresUri
// });

// export async function createTables() {
//     const client = await pool.connect();
//     try {
//         await client.query('BEGIN');

//         await client.query(`CREATE TABLE IF NOT EXISTS "category" (
// 	        "id_category" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
// 	        "product_category" VARCHAR(255) NOT NULL,
// 	        PRIMARY KEY("id_category")`);

//         await client.query(`CREATE TABLE IF NOT EXISTS "supplier" (
//             "id_supplier" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
//             "supplier_name" VARCHAR(255) NOT NULL,
//             "supplier_email" VARCHAR(255) NOT NULL UNIQUE,
//             PRIMARY KEY("id_supplier")`);

//         await client.query(`CREATE TABLE IF NOT EXISTS "customer" (
//             "id_customer" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
//             "customer_name" VARCHAR(255) NOT NULL,
//             "customer_email" VARCHAR(255) NOT NULL UNIQUE,
//             "customer_address" VARCHAR(255) NOT NULL,
//             "customer_phone" VARCHAR(255) NOT NULL,
//             PRIMARY KEY("id_customer")`);

//         await client.query(`CREATE TABLE IF NOT EXISTS "transaction" (
//             "transaction_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
//             "fecha" DATE NOT NULL,
//             "id_customer" INTEGER NOT NULL`);

//         await client.query(`CREATE TABLE IF NOT EXISTS "transaction_details" (
//             "transaction_details_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
//             "quantity" INTEGER NOT NULL,
//             "total" DECIMAL NOT NULL,
//             "transaction_id" INTEGER NOT NULL,
//             "id_product" INTEGER NOT NULL,
//             PRIMARY KEY("transaction_details_id")`);

//         await client.query(`CREATE TABLE IF NOT EXISTS "product" (
//             "id_product" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
//             "product_sku" VARCHAR(255) NOT NULL UNIQUE,
//             "product_name" VARCHAR(255) NOT NULL,
//             "unit_price" VARCHAR(255) NOT NULL,
//             "id_category" INTEGER NOT NULL,
//             "id_supplier" INTEGER NOT NULL,
//             PRIMARY KEY("id_product")`);

//         // ── Indexes for frequent queries ──
//         await client.query(`CREATE INDEX IF NOT EXISTS idx_transaction_customer ON transaction(customer_id)`);
//         await client.query(`CREATE INDEX IF NOT EXISTS idx_transaction_date ON transaction(date)`);
//         await client.query(`CREATE INDEX IF NOT EXISTS idx_transaction_customer_date ON transaction(customer_id, date)`);
//         await client.query(`CREATE INDEX IF NOT EXISTS idx_transaction_details_transaction ON transaction_details(product_id)`);
//         await client.query(`CREATE INDEX IF NOT EXISTS idx_product_category ON product(id_category)`);
//         await client.query(`CREATE INDEX IF NOT EXISTS idx_product_supplier ON product(id_supplier)`);

//         await client.query('COMMIT');

//         console.log('Tables created successfully');

//     } catch (error) {
//         console.error("Error creating tables", error);
//         await client.query("ROLLBACK");

//     } finally {
//         client.release();//liberar la conexión
//     }
// };
