import pg from 'pg';
import { env } from "./env.js";

const { Pool } = pg;

export const pool = new Pool({
    connectionString: env.postgresUri
});

export async function createTables() {
    const client = await pool.connect();
    try {
        await client.query('BEGIN');

        await client.query(`CREATE TABLE IF NOT EXISTS "category" (
	        "id_category" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	        "product_category" VARCHAR(255) NOT NULL,
	        PRIMARY KEY("id_category")`);

        await client.query(`CREATE TABLE IF NOT EXISTS "supplier" (
            "id_supplier" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
            "supplier_name" VARCHAR(255) NOT NULL,
            "supplier_email" VARCHAR(255) NOT NULL UNIQUE,
            PRIMARY KEY("id_supplier")`);

        await client.query(`CREATE TABLE IF NOT EXISTS "customer" (
            "id_customer" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
            "customer_name" VARCHAR(255) NOT NULL,
            "customer_email" VARCHAR(255) NOT NULL UNIQUE,
            "customer_address" VARCHAR(255) NOT NULL,
            "customer_phone" VARCHAR(255) NOT NULL,
            PRIMARY KEY("id_customer")`);

        await client.query(`CREATE TABLE IF NOT EXISTS "transaction" (
            "transaction_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
            "fecha" DATE NOT NULL,
            "id_customer" INTEGER NOT NULL`);

        await client.query(`CREATE TABLE IF NOT EXISTS "transaction_details" (
            "transaction_details_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
            "quantity" INTEGER NOT NULL,
            "total" DECIMAL NOT NULL,
            "transaction_id" INTEGER NOT NULL,
            "id_product" INTEGER NOT NULL,
            PRIMARY KEY("transaction_details_id")`);

        await client.query(`CREATE TABLE IF NOT EXISTS "product" (
            "id_product" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
            "product_sku" VARCHAR(255) NOT NULL UNIQUE,
            "product_name" VARCHAR(255) NOT NULL,
            "unit_price" VARCHAR(255) NOT NULL,
            "id_category" INTEGER NOT NULL,
            "id_supplier" INTEGER NOT NULL,
            PRIMARY KEY("id_product")`);

        // ── Indexes for frequent queries ──
        await client.query(`CREATE INDEX IF NOT EXISTS idx_transaction_customer ON transaction(customer_id)`);
        await client.query(`CREATE INDEX IF NOT EXISTS idx_transaction_date ON transaction(date)`);
        await client.query(`CREATE INDEX IF NOT EXISTS idx_transaction_customer_date ON transaction(customer_id, date)`);
        await client.query(`CREATE INDEX IF NOT EXISTS idx_transaction_details_transaction ON transaction_details(product_id)`);
        await client.query(`CREATE INDEX IF NOT EXISTS idx_product_category ON product(id_category)`);
        await client.query(`CREATE INDEX IF NOT EXISTS idx_product_supplier ON product(id_supplier)`);

        await client.query('COMMIT');

        console.log('Tables created successfully');

    } catch (error) {
        console.error("Error creating tables", error);
        await client.query("ROLLBACK");

    } finally {
        client.release();//liberar la conexión
    }
};