-- NIVEL 1: Tablas que no dependen de nadie
CREATE TABLE IF NOT EXISTS "customer" (
    "id_customer" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "customer_name" VARCHAR(255) NOT NULL,
    "customer_email" VARCHAR(255) NOT NULL UNIQUE,
    "customer_address" VARCHAR(255) NOT NULL,
    "customer_phone" VARCHAR(255) NOT NULL,
    PRIMARY KEY("id_customer")
);

CREATE TABLE IF NOT EXISTS "supplier" (
    "id_supplier" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "supplier_name" VARCHAR(255) NOT NULL,
    "supplier_email" VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY("id_supplier")
);

CREATE TABLE IF NOT EXISTS "category" (
    "id_category" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "product_category" VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY("id_category")
);

-- NIVEL 2: Tablas que dependen del Nivel 1
CREATE TABLE IF NOT EXISTS "product" (
    "id_product" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "product_sku" VARCHAR(255) NOT NULL UNIQUE,
    "product_name" VARCHAR(255) NOT NULL,
    "unit_price" DECIMAL(10,2) NOT NULL,
    "id_category" INTEGER NOT NULL,
    "id_supplier" INTEGER NOT NULL,
    PRIMARY KEY("id_product"),
    FOREIGN KEY("id_supplier") REFERENCES "supplier"("id_supplier"),
    FOREIGN KEY("id_category") REFERENCES "category"("id_category")
);

-- NIVEL 3: Tablas que dependen de Clientes
CREATE TABLE IF NOT EXISTS "transaction" (
    "transaction_id" VARCHAR(255) NOT NULL UNIQUE,
    "fecha" DATE NOT NULL,
    "id_customer" INTEGER NOT NULL,
    PRIMARY KEY("transaction_id"),
    FOREIGN KEY("id_customer") REFERENCES "customer"("id_customer")
);

-- NIVEL 4: Tabla de detalle (La más dependiente)
CREATE TABLE IF NOT EXISTS "transaction_details" (
    "transaction_details_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "quantity" INTEGER NOT NULL,
    "total" DECIMAL(10,2) NOT NULL,
    "transaction_id" VARCHAR(255) NOT NULL,
    "id_product" INTEGER NOT NULL,
    PRIMARY KEY("transaction_details_id"),
    FOREIGN KEY("transaction_id") REFERENCES "transaction"("transaction_id"),
    FOREIGN KEY("id_product") REFERENCES "product"("id_product")
);


-- 1. Relación Transacción -> Cliente
ALTER TABLE "transaction"
ADD CONSTRAINT fk_transaction_customer -- Es mejor ponerles nombre a las restricciones
FOREIGN KEY("id_customer") 
REFERENCES "customer"("id_customer")
ON UPDATE CASCADE 
ON DELETE RESTRICT; -- No deja borrar un cliente si tiene transacciones

-- 2. Relación Detalle -> Transacción (CRUCIAL: ambos deben ser VARCHAR)
ALTER TABLE "transaction_details"
ADD CONSTRAINT fk_details_transaction
FOREIGN KEY("transaction_id") 
REFERENCES "transaction"("transaction_id")
ON UPDATE CASCADE 
ON DELETE CASCADE; -- Si borras la factura, se borran sus detalles automáticamente

-- 3. Relación Detalle -> Producto
ALTER TABLE "transaction_details"
ADD CONSTRAINT fk_details_product
FOREIGN KEY("id_product") 
REFERENCES "product"("id_product")
ON UPDATE CASCADE 
ON DELETE RESTRICT;

-- 4. Relación Producto -> Proveedor
ALTER TABLE "product"
ADD CONSTRAINT fk_product_supplier
FOREIGN KEY("id_supplier") 
REFERENCES "supplier"("id_supplier")
ON UPDATE CASCADE 
ON DELETE RESTRICT;

-- 5. Relación Producto -> Categoría
ALTER TABLE "product"
ADD CONSTRAINT fk_product_category
FOREIGN KEY("id_category") 
REFERENCES "category"("id_category")
ON UPDATE CASCADE 
ON DELETE RESTRICT;