CREATE TABLE IF NOT EXISTS "customer" (
	"id_customer" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"customer_name" VARCHAR(255) NOT NULL,
	"customer_email" VARCHAR(255) NOT NULL UNIQUE,
	"customer_address" VARCHAR(255) NOT NULL,
	"customer_phone" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id_customer")
);




CREATE TABLE IF NOT EXISTS "supplier" (
	"id_supplier" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"supplier_name" VARCHAR(255) NOT NULL,
	"supplier_email" VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY("id_supplier")
);




CREATE TABLE IF NOT EXISTS "product" (
	"id_product" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"product_sku" VARCHAR(255) NOT NULL UNIQUE,
	"product_name" VARCHAR(255) NOT NULL,
	"unit_price" VARCHAR(255) NOT NULL,
	"id_category" INTEGER NOT NULL,
	"id_supplier" INTEGER NOT NULL,
	PRIMARY KEY("id_product")
);




CREATE TABLE IF NOT EXISTS "transaction" (
	"transaction_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"fecha" DATE NOT NULL,
	"id_customer" INTEGER NOT NULL
);




CREATE TABLE IF NOT EXISTS "category" (
	"id_category" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"product_category" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id_category")
);




CREATE TABLE IF NOT EXISTS "transaction_details" (
	"transaction_details_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"quantity" INTEGER NOT NULL,
	"total" DECIMAL NOT NULL,
	"transaction_id" INTEGER NOT NULL,
	"id_product" INTEGER NOT NULL,
	PRIMARY KEY("transaction_details_id")
);



ALTER TABLE "transaction"
ADD FOREIGN KEY("id_customer") REFERENCES "customer"("id_customer")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "transaction_details"
ADD FOREIGN KEY("transaction_id") REFERENCES "transaction"("transaction_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "transaction_details"
ADD FOREIGN KEY("id_product") REFERENCES "product"("id_product")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "product"
ADD FOREIGN KEY("id_supplier") REFERENCES "supplier"("id_supplier")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "product"
ADD FOREIGN KEY("id_category") REFERENCES "category"("id_category")
ON UPDATE NO ACTION ON DELETE NO ACTION;