import { pool } from '../config/postgres.js';

/**
 * SERVICIO DE INICIALIZACIÓN DE BASE DE DATOS
 * Este archivo se encarga de crear la estructura de tablas si no existe.
 */

export const initDatabase = async () => {
    // 1. Obtenemos un cliente del pool para manejar la transacción
    const client = await pool.connect();

    try {
        console.log("⏳ Iniciando creación de tablas en PostgreSQL...");

        // 2. Iniciamos una TRANSACCIÓN
        // Esto asegura que si una tabla falla, no se cree ninguna, manteniendo la DB limpia.
        await client.query('BEGIN');

        // 3. CREACIÓN DE TABLAS INDEPENDIENTES (Nivel 1)
        // Estas tablas no dependen de nadie, se crean primero.
        
        await client.query(`
            CREATE TABLE IF NOT EXISTS "customer" (
                "id_customer" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                "customer_name" VARCHAR(255) NOT NULL,
                "customer_email" VARCHAR(255) NOT NULL UNIQUE,
                "customer_address" VARCHAR(255) NOT NULL,
                "customer_phone" VARCHAR(255) NOT NULL,
                PRIMARY KEY("id_customer")
            );
        `);

        await client.query(`
            CREATE TABLE IF NOT EXISTS "supplier" (
                "id_supplier" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                "supplier_name" VARCHAR(255) NOT NULL,
                "supplier_email" VARCHAR(255) NOT NULL UNIQUE,
                PRIMARY KEY("id_supplier")
            );
        `);

        await client.query(`
            CREATE TABLE IF NOT EXISTS "category" (
                "id_category" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                "product_category" VARCHAR(255) NOT NULL UNIQUE,
                PRIMARY KEY("id_category")
            );
        `);

        // 4. CREACIÓN DE TABLAS DEPENDIENTES (Nivel 2)
        // 'product' necesita que 'category' y 'supplier' existan.
        // Usamos DECIMAL(10,2) para precisión monetaria.

        await client.query(`
            CREATE TABLE IF NOT EXISTS "product" (
                "id_product" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                "product_sku" VARCHAR(255) NOT NULL UNIQUE,
                "product_name" VARCHAR(255) NOT NULL,
                "unit_price" DECIMAL(10,2) NOT NULL, 
                "id_category" INTEGER NOT NULL,
                "id_supplier" INTEGER NOT NULL,
                PRIMARY KEY("id_product"),
                FOREIGN KEY("id_category") REFERENCES "category"("id_category") ON UPDATE CASCADE ON DELETE RESTRICT,
                FOREIGN KEY("id_supplier") REFERENCES "supplier"("id_supplier") ON UPDATE CASCADE ON DELETE RESTRICT
            );
        `);

        // 5. CREACIÓN DE TABLAS DE TRANSACCIONES (Nivel 3)
        // 'transaction' necesita de 'customer'.
        // transaction_id ahora es VARCHAR para soportar los IDs del CSV.

        await client.query(`
            CREATE TABLE IF NOT EXISTS "transaction" (
                "transaction_id" VARCHAR(255) NOT NULL UNIQUE,
                "fecha" DATE NOT NULL,
                "id_customer" INTEGER NOT NULL,
                PRIMARY KEY("transaction_id"),
                FOREIGN KEY("id_customer") REFERENCES "customer"("id_customer") ON UPDATE CASCADE ON DELETE RESTRICT
            );
        `);

        // 6. DETALLE DE TRANSACCIONES (Nivel 4)
        // 'transaction_details' depende de productos y de la tabla 'transaction' (VARCHAR).

        await client.query(`
            CREATE TABLE IF NOT EXISTS "transaction_details" (
                "transaction_details_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                "quantity" INTEGER NOT NULL,
                "total" DECIMAL(10,2) NOT NULL,
                "transaction_id" VARCHAR(255) NOT NULL,
                "id_product" INTEGER NOT NULL,
                PRIMARY KEY("transaction_details_id"),
                FOREIGN KEY("transaction_id") REFERENCES "transaction"("transaction_id") ON UPDATE CASCADE ON DELETE CASCADE,
                FOREIGN KEY("id_product") REFERENCES "product"("id_product") ON UPDATE CASCADE ON DELETE RESTRICT
            );
        `);

        // 7. FINALIZAR TRANSACCIÓN
        // Si todo salió bien, guardamos los cambios permanentemente.
        await client.query('COMMIT');
        console.log(`\x1b[32m%s\x1b[0m`, "✅ Todas las tablas han sido verificadas/creadas con éxito.");

    } catch (error) {
        // Si algo falla, deshacemos todo para no dejar tablas rotas o incompletas.
        await client.query('ROLLBACK');
        console.error(`\x1b[31m%s\x1b[0m`, "❌ Error crítico al crear las tablas:");
        console.error(error.message);
    } finally {
        // MUY IMPORTANTE: Liberar el cliente para que el Pool pueda reusarlo.
        client.release();
    }
};